export const planos = [
  {
    id: "1",
    nome: "Plano 15 dias",
    diasMaximos: 15,
    pontos: 15,
    beneficios: "5% de desconto",
    imagem: null,
  },
  {
    id: "2",
    nome: "Plano 30 dias",
    diasMaximos: 30,
    pontos: 30,
    beneficios: "10% de desconto",
    imagem: null,
  },
  {
    id: "3",
    nome: "Plano 45 dias",
    diasMaximos: 45,
    pontos: 45,
    beneficios: "15% de desconto",
    imagem: null,
  },
  {
    id: "4",
    nome: "Plano 15 dias",
    diasMaximos: 15,
    pontos: 30,
    beneficios: "10% de desconto",
    imagem: null,
  },
  {
    id: "5",
    nome: "Plano 30 dias",
    diasMaximos: 30,
    pontos: 60,
    beneficios: "20% de desconto",
    imagem: null,
  },
  {
    id: "6",
    nome: "Plano 45 dias",
    diasMaximos: 45,
    pontos: 90,
    beneficios: "30% de desconto",
    imagem: null,
  },
];
